-- ─────────────────────────────────────────────────────────────
-- VORA — Seed de catálogos (Fase 3)
-- Generado por scripts/gen-seed.mjs — no editar a mano.
-- ─────────────────────────────────────────────────────────────

-- slug único para el motor y el linkeo de planned_exercises
alter table public.exercises add column if not exists slug text;
create unique index if not exists exercises_slug_key on public.exercises (slug) where slug is not null;

insert into public.exercises (slug, name, primary_muscle, secondary_muscles, equipment, difficulty, movement_pattern, variation_group, cues) values
  ('barbell-bench-press', 'Press banca con barra', 'pecho', '{hombros,tríceps}', 'gym', 'beginner', 'push', 'horizontal_push', null),
  ('dumbbell-bench-press', 'Press banca con mancuernas', 'pecho', '{hombros,tríceps}', 'home_dumbbells', 'beginner', 'push', 'horizontal_push', null),
  ('machine-chest-press', 'Press pecho en máquina', 'pecho', '{tríceps}', 'gym', 'beginner', 'push', 'horizontal_push', null),
  ('push-up', 'Lagartijas', 'pecho', '{hombros,tríceps,core}', 'home_minimal', 'beginner', 'push', 'horizontal_push', 'Cuerpo en línea recta, baja hasta que el pecho toque el piso.'),
  ('incline-barbell-press', 'Press inclinado con barra', 'pecho superior', '{hombros}', 'gym', 'intermediate', 'push', 'incline_push', null),
  ('incline-dumbbell-press', 'Press inclinado con mancuernas', 'pecho superior', '{hombros,tríceps}', 'home_dumbbells', 'beginner', 'push', 'incline_push', null),
  ('dips', 'Fondos en paralelas', 'pecho inferior', '{tríceps,hombros}', 'gym', 'intermediate', 'push', 'dips', null),
  ('bench-dips', 'Fondos en banca', 'tríceps', '{pecho}', 'home_minimal', 'beginner', 'push', 'dips', null),
  ('barbell-overhead-press', 'Press militar con barra', 'hombros', '{tríceps}', 'gym', 'beginner', 'push', 'vertical_push', null),
  ('dumbbell-shoulder-press', 'Press de hombros con mancuernas', 'hombros', '{tríceps}', 'home_dumbbells', 'beginner', 'push', 'vertical_push', null),
  ('machine-shoulder-press', 'Press de hombros en máquina', 'hombros', '{tríceps}', 'gym', 'beginner', 'push', 'vertical_push', null),
  ('pike-push-up', 'Lagartijas en pico', 'hombros', '{tríceps}', 'home_minimal', 'intermediate', 'push', 'vertical_push', null),
  ('lateral-raise', 'Elevaciones laterales', 'hombro lateral', '{}', 'home_dumbbells', 'beginner', 'push', 'lateral_raise', null),
  ('cable-lateral-raise', 'Elevaciones laterales en polea', 'hombro lateral', '{}', 'gym', 'intermediate', 'push', 'lateral_raise', null),
  ('front-raise', 'Elevaciones frontales', 'hombro frontal', '{}', 'home_dumbbells', 'beginner', 'push', 'front_raise', null),
  ('rear-delt-fly', 'Vuelos posteriores', 'hombro posterior', '{espalda alta}', 'home_dumbbells', 'beginner', 'pull', 'rear_delt', null),
  ('face-pull', 'Face pull en polea', 'hombro posterior', '{espalda alta}', 'gym', 'intermediate', 'pull', 'rear_delt', null),
  ('cable-fly', 'Aperturas en polea', 'pecho', '{}', 'gym', 'intermediate', 'push', 'fly', null),
  ('pec-deck', 'Pecho en máquina (peck deck)', 'pecho', '{}', 'gym', 'beginner', 'push', 'fly', null),
  ('dumbbell-fly', 'Aperturas con mancuernas', 'pecho', '{}', 'home_dumbbells', 'intermediate', 'push', 'fly', null),
  ('dumbbell-pullover', 'Pullover con mancuerna', 'pecho', '{dorsales}', 'home_dumbbells', 'intermediate', 'push', 'pullover', null),
  ('triceps-pushdown', 'Extensiones de tríceps en polea', 'tríceps', '{}', 'gym', 'beginner', 'push', 'triceps_pressdown', null),
  ('dumbbell-overhead-extension', 'Extensión de tríceps sobre la cabeza', 'tríceps', '{}', 'home_dumbbells', 'intermediate', 'push', 'triceps_pressdown', null),
  ('skull-crusher', 'Rompe cráneos (acostado)', 'tríceps', '{}', 'gym', 'intermediate', 'push', 'triceps_pressdown', null),
  ('pull-up', 'Dominadas', 'dorsales', '{bíceps,espalda media}', 'gym', 'intermediate', 'pull', 'vertical_pull', null),
  ('chin-up', 'Dominadas supinas', 'dorsales', '{bíceps}', 'gym', 'intermediate', 'pull', 'vertical_pull', null),
  ('lat-pulldown', 'Jalón al pecho', 'dorsales', '{bíceps}', 'gym', 'beginner', 'pull', 'vertical_pull', null),
  ('assisted-pull-up', 'Dominadas asistidas', 'dorsales', '{bíceps}', 'gym', 'beginner', 'pull', 'vertical_pull', null),
  ('inverted-row', 'Remo invertido', 'espalda media', '{dorsales,bíceps}', 'home_minimal', 'beginner', 'pull', 'row', null),
  ('barbell-row', 'Remo con barra', 'espalda media', '{dorsales,bíceps}', 'gym', 'intermediate', 'pull', 'row', null),
  ('dumbbell-row', 'Remo con mancuerna', 'espalda media', '{dorsales,bíceps}', 'home_dumbbells', 'beginner', 'pull', 'row', null),
  ('cable-seated-row', 'Remo sentado en polea', 'espalda media', '{dorsales,bíceps}', 'gym', 'beginner', 'pull', 'row', null),
  ('machine-row', 'Remo en máquina', 'espalda media', '{dorsales}', 'gym', 'beginner', 'pull', 'row', null),
  ('one-arm-dumbbell-row', 'Remo a un brazo', 'dorsales', '{espalda media}', 'home_dumbbells', 'beginner', 'pull', 'row', null),
  ('barbell-deadlift', 'Peso muerto con barra', 'isquiotibiales', '{glúteos,espalda,core}', 'gym', 'intermediate', 'pull', 'deadlift', 'Espalda neutral, la barra pega a las piernas.'),
  ('romanian-deadlift', 'Peso muerto rumano', 'isquiotibiales', '{glúteos}', 'gym', 'intermediate', 'pull', 'deadlift', null),
  ('dumbbell-rdl', 'Peso muerto rumano con mancuernas', 'isquiotibiales', '{glúteos}', 'home_dumbbells', 'beginner', 'pull', 'deadlift', null),
  ('barbell-curl', 'Curl con barra', 'bíceps', '{}', 'gym', 'beginner', 'pull', 'biceps_curl', null),
  ('dumbbell-curl', 'Curl con mancuernas', 'bíceps', '{}', 'home_dumbbells', 'beginner', 'pull', 'biceps_curl', null),
  ('cable-curl', 'Curl en polea', 'bíceps', '{}', 'gym', 'beginner', 'pull', 'biceps_curl', null),
  ('hammer-curl', 'Curl martillo', 'braquial', '{bíceps}', 'home_dumbbells', 'beginner', 'pull', 'biceps_curl', null),
  ('barbell-back-squat', 'Sentadilla trasera', 'cuádriceps', '{glúteos,isquiotibiales}', 'gym', 'intermediate', 'legs', 'squat', null),
  ('goblet-squat', 'Sentadilla goblet', 'cuádriceps', '{glúteos}', 'home_dumbbells', 'beginner', 'legs', 'squat', null),
  ('bodyweight-squat', 'Sentadilla a peso corporal', 'cuádriceps', '{glúteos}', 'home_minimal', 'beginner', 'legs', 'squat', null),
  ('leg-press', 'Prensa de pierna', 'cuádriceps', '{glúteos}', 'gym', 'beginner', 'legs', 'squat', null),
  ('bulgarian-split-squat', 'Sentadilla búlgara', 'cuádriceps', '{glúteos}', 'home_dumbbells', 'intermediate', 'legs', 'lunge', null),
  ('dumbbell-lunge', 'Zancadas con mancuernas', 'cuádriceps', '{glúteos}', 'home_dumbbells', 'beginner', 'legs', 'lunge', null),
  ('walking-lunge', 'Zancadas caminando', 'cuádriceps', '{glúteos}', 'home_minimal', 'beginner', 'legs', 'lunge', null),
  ('step-up', 'Subir a un escalón', 'cuádriceps', '{glúteos}', 'home_minimal', 'beginner', 'legs', 'lunge', null),
  ('hip-thrust', 'Empuje de cadera con barra', 'glúteos', '{isquiotibiales}', 'gym', 'beginner', 'legs', 'glute_hinge', null),
  ('dumbbell-hip-thrust', 'Empuje de cadera con mancuernas', 'glúteos', '{isquiotibiales}', 'home_dumbbells', 'beginner', 'legs', 'glute_hinge', null),
  ('glute-bridge', 'Puente de glúteo', 'glúteos', '{isquiotibiales,core}', 'home_minimal', 'beginner', 'legs', 'glute_hinge', null),
  ('leg-extension', 'Extensión de cuádriceps', 'cuádriceps', '{}', 'gym', 'beginner', 'legs', 'quad_iso', null),
  ('leg-curl', 'Curl femoral', 'isquiotibiales', '{}', 'gym', 'beginner', 'legs', 'ham_iso', null),
  ('nordic-curl', 'Curl nórdico', 'isquiotibiales', '{}', 'home_minimal', 'advanced', 'legs', 'ham_iso', null),
  ('standing-calf-raise', 'Elevación de gemelos de pie', 'gemelos', '{}', 'home_minimal', 'beginner', 'legs', 'calf', null),
  ('seated-calf-raise', 'Elevación de gemelos sentado', 'gemelos', '{}', 'gym', 'beginner', 'legs', 'calf', null),
  ('plank', 'Plancha', 'abdomen', '{core}', 'home_minimal', 'beginner', 'core', 'plank', 'Glúteos apretados, no dejes caer la cadera.'),
  ('side-plank', 'Plancha lateral', 'oblicuos', '{core}', 'home_minimal', 'beginner', 'core', 'plank', null),
  ('hanging-leg-raise', 'Elevación de piernas colgado', 'abdomen', '{flexores de cadera}', 'gym', 'intermediate', 'core', 'leg_raise', null),
  ('lying-leg-raise', 'Elevación de piernas acostado', 'abdomen', '{}', 'home_minimal', 'beginner', 'core', 'leg_raise', null),
  ('cable-crunch', 'Crunch en polea', 'abdomen', '{}', 'gym', 'beginner', 'core', 'crunch', null),
  ('russian-twist', 'Giros rusos', 'oblicuos', '{abdomen}', 'home_minimal', 'beginner', 'core', 'crunch', null),
  ('ab-wheel', 'Rueda abdominal', 'abdomen', '{core}', 'home_minimal', 'intermediate', 'core', 'crunch', null),
  ('pallof-press', 'Pallof press', 'oblicuos', '{core}', 'gym', 'beginner', 'core', 'anti_rotation', null),
  ('farmer-carry', 'Carga del granjero con mancuernas', 'agarre', '{trapecios,core}', 'gym', 'beginner', 'carry', 'carry', null),
  ('dumbbell-farmer-carry', 'Carga del granjero', 'agarre', '{trapecios,core}', 'home_dumbbells', 'beginner', 'carry', 'carry', null),
  ('suitcase-carry', 'Carga maleta', 'oblicuos', '{agarre}', 'home_dumbbells', 'intermediate', 'carry', 'carry', null)
on conflict (slug) where slug is not null do nothing;

-- alimentos seed: fuente única de la sección de presupuesto
create unique index if not exists foods_seed_name_key on public.foods (name) where source = 'seed';
alter table public.foods add column if not exists vegan boolean default true;
alter table public.foods add column if not exists vegetarian boolean default true;

insert into public.foods (name, calories, protein_g, carbs_g, fat_g, serving_g, category, price_mxn, vegan, vegetarian, source) values
  ('Pechuga de pollo', 115, 23, 0, 1.5, 150, 'protein', 4.5, false, false, 'seed'),
  ('Huevo', 143, 12.6, 0.7, 9.5, 50, 'protein', 1.8, false, true, 'seed'),
  ('Atún en agua (lata)', 116, 26, 0, 1, 100, 'protein', 18, false, false, 'seed'),
  ('Carne de res magra', 187, 26, 0, 9, 150, 'protein', 15, false, false, 'seed'),
  ('Camarón', 99, 24, 0, 0.3, 150, 'protein', 20, false, false, 'seed'),
  ('Sardina en lata', 208, 25, 0, 11, 100, 'protein', 18, false, false, 'seed'),
  ('Tofu firme', 144, 16, 2, 9, 150, 'protein', 6, true, true, 'seed'),
  ('Lentejas cocidas', 116, 9, 20, 0.4, 200, 'protein', 3, true, true, 'seed'),
  ('Frijoles negros cocidos', 132, 9, 24, 0.5, 200, 'protein', 3.5, true, true, 'seed'),
  ('Garbanzos cocidos', 164, 9, 27, 2.6, 200, 'protein', 4, true, true, 'seed'),
  ('Queso panela', 174, 22, 0, 9, 80, 'protein', 16, false, true, 'seed'),
  ('Yogurt griego natural', 59, 10, 3.6, 0.4, 170, 'protein', 9, false, true, 'seed'),
  ('Proteína whey', 400, 80, 8, 6, 30, 'protein', 50, false, true, 'seed'),
  ('Arroz blanco cocido', 130, 2.7, 28, 0.3, 200, 'carbs', 1.5, true, true, 'seed'),
  ('Avena', 389, 17, 66, 7, 80, 'carbs', 3.5, true, true, 'seed'),
  ('Tortilla de maíz', 218, 5, 45, 3, 150, 'carbs', 2.5, true, true, 'seed'),
  ('Papa cocida', 87, 2, 20, 0.1, 200, 'carbs', 2.5, true, true, 'seed'),
  ('Camote', 86, 1.6, 20, 0.1, 200, 'carbs', 2.5, true, true, 'seed'),
  ('Pan integral', 247, 13, 41, 3.4, 60, 'carbs', 6, false, true, 'seed'),
  ('Pasta cocida', 158, 5.8, 31, 0.9, 200, 'carbs', 2, true, true, 'seed'),
  ('Quinoa cocida', 120, 4.4, 21, 1.9, 150, 'carbs', 9, true, true, 'seed'),
  ('Brócoli', 34, 2.8, 7, 0.4, 150, 'veggie', 3.5, true, true, 'seed'),
  ('Espinaca', 23, 2.9, 3.6, 0.4, 100, 'veggie', 3, true, true, 'seed'),
  ('Zanahoria', 41, 0.9, 10, 0.2, 100, 'veggie', 2, true, true, 'seed'),
  ('Ensalada mixta', 18, 1, 3.5, 0.2, 150, 'veggie', 2.5, true, true, 'seed'),
  ('Aguacate', 160, 2, 9, 15, 80, 'fat', 9, true, true, 'seed'),
  ('Cacahuate', 567, 26, 16, 49, 30, 'fat', 6, true, true, 'seed'),
  ('Aceite de oliva', 884, 0, 0, 100, 15, 'fat', 25, true, true, 'seed'),
  ('Almendras', 579, 21, 22, 50, 30, 'fat', 30, true, true, 'seed'),
  ('Plátano', 89, 1.1, 23, 0.3, 120, 'fruit', 2.5, true, true, 'seed'),
  ('Manzana', 52, 0.3, 14, 0.2, 180, 'fruit', 3, true, true, 'seed')
on conflict (name) where source = 'seed' do nothing;
